backend:
  name: github
  repo: jethromay/jethromay.com
  branch: master

media_folder: static/assets

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }